Popup:
  title: "Unsaved edits"
  size_hint: .8, .6
  
  GridLayout:
    cols: 1
    
    Label:
      text: "You need to save your project before you run it\nSave changes ?"
    
    GridLayout:
      rows: 1
      
      Button:
        text: "No"
        on_release:
          root.dismiss()

      Button:
        text: "Yes"
        on_release:
          root.dismiss()
          app.save_project()
          app.run_code()