<ProjectScreen>:
  action_bar: action_bar
  project_grid: project_grid
  GridLayout:
    id: Main
    cols: 1

    GridLayout:
      id: action_bar
      size_hint_y: 0.175
      rows: 1

      Button:
        text: "New project"
        on_release:
          root.new_project_popup()
      Button:
        text: "Settings"
        on_release:
          app.open_settings()

    ScrollView:
      do_scroll_x: False
      GridLayout:
        id: project_grid
        size_hint_y: 1
        cols: 1
